name: build and push images

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        stage: [backup, restore]
        include:
          - { postgres: 11, alpine: "3.10" }
          - { postgres: 12, alpine: "3.12" }
          - { postgres: 13, alpine: "3.14" }
          - { postgres: 14, alpine: "3.16" }
          - { postgres: 15, alpine: "3.17" }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ github.repository_owner }}/postgres-${{ matrix.stage }}-s3:${{ matrix.postgres }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha,scope=${{ matrix.stage }}-${{ matrix.postgres }}
          cache-to: type=gha,mode=max,scope=${{ matrix.stage }}-${{ matrix.postgres }}
